# Generated by Django 5.2.4 on 2025-08-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_COMERCIAL', 'Ingeniería Comercial'), ('ING_CIVIL', 'Ingeniería Civil'), ('ING_PETROLERA', 'Ingeniería Petrolera'), ('ING_QUIMICA', 'Ingeniería Química'), ('ING_MECATRONICA', 'Ingeniería Mecatrónica'), ('LIC_BIOTECNOLOGIA', 'Licenciatura en Biotecnología'), ('ING_FORESTAL', 'Ingeniería Forestal'), ('LIC_TURISMO', 'Licenciatura en Turismo'), ('ING_ZOOTECNIA', 'Ingeniería Zootécnica'), ('MED_VETERINARIA', 'Medicina Veterinaria y Zootecnia'), ('ING_SISTEMAS_RIBE', 'Ingeniería de Sistemas (Riberalta)'), ('ING_COMERCIAL_RIBE', 'Ingeniería Comercial (Riberalta)'), ('ING_SISTEMAS_TROP', 'Ingeniería de Sistemas (Trópico)'), ('ING_SISTEMAS_CBBA', 'Ingeniería de Sistemas (Cochabamba)'), ('ING_INDUSTRIAL_CBBA', 'Ingeniería Industrial (Cochabamba)'), ('ING_COMERCIAL_CBBA', 'Ingeniería Comercial (Cochabamba)')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('LAB_FISICA_1', 'Laboratorio de Física Piso 1'), ('LAB_FISICA_4', 'Laboratorio de Física Piso 4'), ('LAB_QUIMICA', 'Laboratorio de Química'), ('LAB_BIOTECNOLOGIA', 'Laboratorio de Biotecnología'), ('LAB_SISTEMAS_1', 'Laboratorio de Sistemas Piso 1'), ('LAB_SISTEMAS_I', 'Laboratorio de Sistemas I'), ('LAB_MECATRONICA', 'Laboratorio de Mecatrónica'), ('LAB_INDUSTRIAL', 'Laboratorio Industrial'), ('LAB_CIVIL', 'Laboratorio de Civil'), ('LAB_COMERCIAL_301', 'Laboratorio Comercial Aula 301'), ('LAB_EDAFOLOGIA', 'Laboratorio de Edafología'), ('LAB_CIENCIAS_BASICAS', 'Laboratorio de Ciencias Básicas'), ('LAB_PETROLERA', 'Laboratorio Petrolero y Geográfico'), ('OFICINAS_UICYT', 'Oficinas Unidad de Investigación')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del laboratorio', max_length=200)),
                ('capacidad', models.PositiveIntegerField(default=25, help_text='Capacidad de estudiantes')),
                ('responsable', models.CharField(blank=True, help_text='Responsable del laboratorio', max_length=200)),
                ('seccion_area', models.CharField(blank=True, help_text='Sección o área específica', max_length=100)),
                ('identificador_aula', models.CharField(blank=True, help_text='Número de aula o identificador', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('UASC', 'UASC - Unidad Académica Santa Cruz'), ('UARIBE', 'UARIBE - Unidad Académica Riberalta'), ('UATROP', 'UATROP - Unidad Académica Trinidad'), ('UACBBA', 'UACBBA - Unidad Académica Cochabamba')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad Académica',
                'verbose_name_plural': 'Unidades Académicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[], max_length=50)),
                ('semestre', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')])),
                ('carga_horaria_semanal', models.IntegerField(help_text='Horas por semana')),
                ('carga_horaria_semestral', models.IntegerField(help_text='Total de horas en el semestre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['semestre', 'nombre'],
                'unique_together': {('nombre', 'carrera', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='core.unidadacademica'),
        ),
        migrations.CreateModel(
            name='UnidadTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la unidad temática')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_tematicas', to='core.asignatura')),
            ],
            options={
                'verbose_name': 'Unidad Temática',
                'verbose_name_plural': 'Unidades Temáticas',
                'ordering': ['numero'],
                'unique_together': {('asignatura', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GuiaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la guía')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_laboratorio', to='core.unidadtematica')),
            ],
            options={
                'verbose_name': 'Guía de Laboratorio',
                'verbose_name_plural': 'Guías de Laboratorio',
                'ordering': ['numero'],
                'unique_together': {('unidad_tematica', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la práctica')),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='core.guialaboratorio')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
                'ordering': ['numero'],
                'unique_together': {('guia_laboratorio', 'numero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('unidad_academica', 'nombre')},
        ),
    ]
