# Generated by Django 5.2.4 on 2025-08-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(choices=[('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_COMERCIAL', 'Ingeniería Comercial'), ('ING_CIVIL', 'Ingeniería Civil'), ('ING_PETROLERA', 'Ingeniería Petrolera'), ('ING_QUIMICA', 'Ingeniería Química'), ('ING_MECATRONICA', 'Ingeniería Mecatrónica'), ('LIC_BIOTECNOLOGIA', 'Licenciatura en Biotecnología'), ('ING_SISTEMAS_RIBE', 'Ingeniería de Sistemas (Riberalta)'), ('ING_COMERCIAL_RIBE', 'Ingeniería Comercial (Riberalta)'), ('ING_SISTEMAS_TROP', 'Ingeniería de Sistemas (Trópico)'), ('ING_SISTEMAS_CBBA', 'Ingeniería de Sistemas (Cochabamba)'), ('ING_INDUSTRIAL_CBBA', 'Ingeniería Industrial (Cochabamba)'), ('ING_COMERCIAL_CBBA', 'Ingeniería Comercial (Cochabamba)')], max_length=50),
        ),
    ]
