# Generated by Django 5.2.4 on 2025-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrera_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(choices=[('ING_CIVIL', 'Ingeniería Civil'), ('ING_COMERCIAL', 'Ingeniería Comercial'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_MECANICA', 'Ingeniería Mecánica'), ('ING_MECATRONICA', 'Ingeniería Mecatrónica'), ('ING_PETROLERA', 'Ingeniería Petrolera'), ('ING_QUIMICA', 'Ingeniería Química'), ('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('TEC_ELECTRONICA', 'Técnico Superior en Electrónica'), ('TEC_MECANICA', 'Técnico Superior en Mecánica Industrial'), ('TEC_CONSTRUCCIONES', 'Técnico Superior en Construcciones Civiles'), ('TEC_ELECTROMECANICA', 'Técnico Superior en Electromecánica'), ('TEC_QUIMICA', 'Técnico Superior en Química Industrial'), ('TEC_SISTEMAS', 'Técnico Superior en Sistemas'), ('TEC_TOPOGRAFIA', 'Técnico Superior en Topografía'), ('LIC_BIOTECNOLOGIA', 'Licenciatura en Biotecnología'), ('MEDICINA', 'Medicina'), ('ENFERMERIA', 'Enfermería'), ('DERECHO', 'Derecho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='unidadacademica',
            name='nombre',
            field=models.CharField(choices=[('UALP', 'UALP - La Paz'), ('UACB', 'UACB - Cochabamba'), ('UASC', 'UASC - Santa Cruz'), ('UATP', 'UATP - Trópico'), ('UCRB', 'UCRB - Riberalta')], max_length=20, unique=True),
        ),
    ]
