# Generated by Django 5.2.4 on 2025-08-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carrera_nombre_alter_unidadacademica_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='carga_horaria_semanal',
            field=models.IntegerField(default=4, help_text='Horas por semana'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='carga_horaria_semestral',
            field=models.IntegerField(default=80, help_text='Total de horas en el semestre'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='core.carrera'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('matematica_i', 'Matemática I'), ('matematica_ii', 'Matemática II'), ('matematica_iii', 'Matemática III'), ('matematica_iv', 'Matemática IV'), ('fisica_i', 'Física I'), ('fisica_ii', 'Física II'), ('fisica_iii', 'Física III'), ('quimica_general', 'Química General'), ('quimica_organica', 'Química Orgánica'), ('estadistica_probabilidades', 'Estadística y Probabilidades'), ('ecuaciones_diferenciales', 'Ecuaciones Diferenciales'), ('metodos_numericos', 'Métodos Numéricos'), ('programacion_i', 'Programación I'), ('programacion_ii', 'Programación II'), ('bases_datos', 'Bases de Datos'), ('analisis_sistemas', 'Análisis de Sistemas'), ('ingenieria_software', 'Ingeniería de Software'), ('redes_computadoras', 'Redes de Computadoras'), ('sistemas_distribuidos', 'Sistemas Distribuidos'), ('inteligencia_artificial', 'Inteligencia Artificial'), ('simulacion_sistemas', 'Simulación de Sistemas'), ('auditoria_sistemas', 'Auditoría de Sistemas'), ('dibujo_tecnico', 'Dibujo Técnico'), ('mecanica_materiales', 'Mecánica de Materiales'), ('resistencia_materiales', 'Resistencia de Materiales'), ('termodinamica', 'Termodinámica'), ('mecanica_fluidos', 'Mecánica de Fluidos'), ('transferencia_calor', 'Transferencia de Calor'), ('circuitos_electricos', 'Circuitos Eléctricos'), ('electronica_basica', 'Electrónica Básica'), ('sistemas_control', 'Sistemas de Control'), ('automatizacion_industrial', 'Automatización Industrial'), ('economia_ingenieria', 'Economía para Ingeniería'), ('gestion_proyectos', 'Gestión de Proyectos'), ('evaluacion_proyectos', 'Evaluación de Proyectos'), ('formulacion_proyectos', 'Formulación de Proyectos'), ('investigacion_operativa', 'Investigación Operativa'), ('gestion_calidad', 'Gestión de Calidad'), ('calidad_procesos', 'Calidad de Procesos'), ('liderazgo_equipos', 'Liderazgo de Equipos'), ('emprendimiento', 'Emprendimiento'), ('procesos_industriales', 'Procesos Industriales'), ('optimizacion_procesos', 'Optimización de Procesos'), ('mantenimiento_industrial', 'Mantenimiento Industrial'), ('seguridad_industrial', 'Seguridad Industrial'), ('gestion_ambiental', 'Gestión Ambiental'), ('desarrollo_sostenible', 'Desarrollo Sostenible'), ('innovacion_tecnologica', 'Innovación Tecnológica'), ('ingles_tecnico_i', 'Inglés Técnico I'), ('ingles_tecnico_ii', 'Inglés Técnico II'), ('comunicacion_tecnica', 'Comunicación Técnica'), ('metodologia_investigacion', 'Metodología de la Investigación'), ('introduccion_ingenieria', 'Introducción a la Ingeniería'), ('etica_profesional', 'Ética Profesional'), ('legislacion_profesional', 'Legislación Profesional'), ('responsabilidad_social', 'Responsabilidad Social'), ('proyecto_grado_i', 'Proyecto de Grado I'), ('proyecto_grado_ii', 'Proyecto de Grado II'), ('seminario_titulacion', 'Seminario de Titulación'), ('practica_profesional', 'Práctica Profesional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(choices=[('ING_CIVIL', 'Ingeniería Civil'), ('ING_GEOGRAFICA', 'Ingeniería Geográfica'), ('ING_SISTEMAS_ELECTRONICOS', 'Ingeniería en Sistemas Electrónicos'), ('ING_INDUSTRIAL', 'Ingeniería Industrial'), ('ING_COMERCIAL', 'Ingeniería Comercial'), ('ING_SISTEMAS', 'Ingeniería de Sistemas'), ('ING_AMBIENTAL', 'Ingeniería Ambiental'), ('ING_PETROLERA', 'Ingeniería Petrolera'), ('ING_MECATRONICA', 'Ingeniería Mecatrónica'), ('ING_TELECOMUNICACIONES', 'Ingeniería en Telecomunicaciones'), ('ING_FINANCIERA', 'Ingeniería Financiera'), ('ING_AGROINDUSTRIAL', 'Ingeniería Agroindustrial'), ('ING_AGRONOMICA', 'Ingeniería Agronómica'), ('INFORMATICA', 'Informática'), ('SISTEMAS_ELECTRONICOS', 'Sistemas Electrónicos'), ('ENERGIAS_RENOVABLES', 'Energías Renovables'), ('CONSTRUCCION_CIVIL', 'Construcción Civil'), ('DISENO_GRAFICO', 'Diseño Gráfico y Comunicación Audiovisual')], max_length=50),
        ),
    ]
