# Generated by Django 5.2.4 on 2025-08-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asignatura_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(choices=[('LAB_TRATAMIENTO_AGUAS', 'Planta de Tratamiento de Aguas'), ('LAB_ASFALTOS', 'Laboratorio de Asfaltos'), ('LAB_HORMIGONES', 'Laboratorio de Hormigones'), ('LAB_RESISTENCIA_MATERIALES', 'Laboratorio de Resistencia de Materiales y Suelos'), ('LAB_LACTEOS', 'Laboratorio de Lácteos'), ('LAB_FISICA_1', 'Laboratorio de Física Piso 1'), ('LAB_FISICA_4', 'Laboratorio de Física Piso 4'), ('LAB_QUIMICA', 'Laboratorio de Química'), ('LAB_BIOTECNOLOGIA', 'Laboratorio de Biotecnología'), ('LAB_SISTEMAS_1', 'Laboratorio de Sistemas Piso 1'), ('LAB_SISTEMAS_I', 'Laboratorio de Sistemas I'), ('LAB_MECATRONICA', 'Laboratorio de Mecatrónica'), ('LAB_INDUSTRIAL', 'Laboratorio Industrial'), ('LAB_CIVIL', 'Laboratorio de Civil'), ('LAB_COMERCIAL_301', 'Laboratorio Comercial Aula 301'), ('LAB_EDAFOLOGIA', 'Laboratorio de Edafología'), ('LAB_CIENCIAS_BASICAS', 'Laboratorio de Ciencias Básicas'), ('LAB_PETROLERA', 'Laboratorio Petrolero y Geográfico'), ('OFICINAS_UICYT', 'Oficinas Unidad de Investigación')], max_length=50),
        ),
    ]
