# Generated by Django 5.2.4 on 2025-09-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_laboratorio_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Criterio de Desempeño')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_desempeno', to='core.asignatura')),
            ],
            options={
                'verbose_name': 'Criterio de Desempeño',
                'verbose_name_plural': 'Criterios de Desempeño',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadDidactica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Unidad Didáctica')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_didacticas', to='core.asignatura')),
            ],
            options={
                'verbose_name': 'Unidad Didáctica',
                'verbose_name_plural': 'Unidades Didácticas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContenidoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True, verbose_name='Contenido Analítico')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_didactica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_analiticos', to='core.unidaddidactica')),
            ],
            options={
                'verbose_name': 'Contenido Analítico',
                'verbose_name_plural': 'Contenidos Analíticos',
                'ordering': ['nombre'],
            },
        ),
    ]
