# Generated by Django 5.2.4 on 2025-09-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_criteriodesempeno_unidaddidactica_contenidoanalitico'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codigo_competencia',
            field=models.CharField(blank=True, help_text='Código de competencia de la materia', max_length=50, null=True, verbose_name='Código de Competencia'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='sigla_curricular',
            field=models.CharField(blank=True, help_text='Sigla curricular de la asignatura', max_length=50, null=True, verbose_name='Sigla Curricular'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(choices=[('matematica_i', 'Matemática I'), ('matematica_ii', 'Matemática II'), ('matematica_iii', 'Matemática III'), ('matematica_iv', 'Matemática IV'), ('fisica_i', 'Física I'), ('fisica_ii', 'Física II'), ('fisica_iii', 'Física III'), ('quimica_general', 'Química General'), ('fisicoquimica', 'Fisicoquímica'), ('quimica_organica', 'Química Orgánica'), ('estadistica_probabilidades', 'Estadística y Probabilidades'), ('ecuaciones_diferenciales', 'Ecuaciones Diferenciales'), ('metodos_numericos', 'Métodos Numéricos'), ('programacion_i', 'Programación I'), ('programacion_ii', 'Programación II'), ('bases_datos', 'Bases de Datos'), ('analisis_sistemas', 'Análisis de Sistemas'), ('ingenieria_software', 'Ingeniería de Software'), ('redes_computadoras', 'Redes de Computadoras'), ('sistemas_distribuidos', 'Sistemas Distribuidos'), ('inteligencia_artificial', 'Inteligencia Artificial'), ('simulacion_sistemas', 'Simulación de Sistemas'), ('auditoria_sistemas', 'Auditoría de Sistemas'), ('dibujo_tecnico', 'Dibujo Técnico'), ('mecanica_materiales', 'Mecánica de Materiales'), ('resistencia_materiales', 'Resistencia de Materiales'), ('termodinamica', 'Termodinámica'), ('mecanica_fluidos', 'Mecánica de Fluidos'), ('transferencia_calor', 'Transferencia de Calor'), ('circuitos_electricos', 'Circuitos Eléctricos'), ('electronica_basica', 'Electrónica Básica'), ('sistemas_control', 'Sistemas de Control'), ('automatizacion_industrial', 'Automatización Industrial'), ('economia_ingenieria', 'Economía para Ingeniería'), ('gestion_proyectos', 'Gestión de Proyectos'), ('evaluacion_proyectos', 'Evaluación de Proyectos'), ('formulacion_proyectos', 'Formulación de Proyectos'), ('investigacion_operativa', 'Investigación Operativa'), ('gestion_calidad', 'Gestión de Calidad'), ('calidad_procesos', 'Calidad de Procesos'), ('liderazgo_equipos', 'Liderazgo de Equipos'), ('emprendimiento', 'Emprendimiento'), ('procesos_industriales', 'Procesos Industriales'), ('optimizacion_procesos', 'Optimización de Procesos'), ('mantenimiento_industrial', 'Mantenimiento Industrial'), ('seguridad_industrial', 'Seguridad Industrial'), ('gestion_ambiental', 'Gestión Ambiental'), ('desarrollo_sostenible', 'Desarrollo Sostenible'), ('innovacion_tecnologica', 'Innovación Tecnológica'), ('ingles_tecnico_i', 'Inglés Técnico I'), ('ingles_tecnico_ii', 'Inglés Técnico II'), ('comunicacion_tecnica', 'Comunicación Técnica'), ('metodologia_investigacion', 'Metodología de la Investigación'), ('introduccion_ingenieria', 'Introducción a la Ingeniería'), ('etica_profesional', 'Ética Profesional'), ('legislacion_profesional', 'Legislación Profesional'), ('responsabilidad_social', 'Responsabilidad Social'), ('proyecto_grado_i', 'Proyecto de Grado I'), ('proyecto_grado_ii', 'Proyecto de Grado II'), ('seminario_titulacion', 'Seminario de Titulación'), ('practica_profesional', 'Práctica Profesional')], max_length=50),
        ),
    ]
