# Generated by Django 5.2.4 on 2025-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asignatura_codigo_competencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadacademica',
            name='nombre',
            field=models.CharField(choices=[('UALP', 'UALP - La Paz'), ('UACB', 'UACB - Cochabamba'), ('UASC', 'UASC - Santa Cruz'), ('UATP', 'UATP - Trópico'), ('UARB', 'UARB - Riberalta')], max_length=20, unique=True),
        ),
    ]
