# Generated by Django 5.2.4 on 2025-10-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unidadacademica_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título de la bibliografía')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('editorial', models.CharField(blank=True, max_length=200, verbose_name='Editorial')),
                ('año_publicacion', models.IntegerField(blank=True, null=True, verbose_name='Año de publicación')),
                ('paginas', models.CharField(blank=True, max_length=50, verbose_name='Páginas')),
                ('isbn', models.CharField(blank=True, max_length=50, verbose_name='ISBN')),
                ('tipo_referencia', models.CharField(choices=[('libro', 'Libro'), ('articulo', 'Artículo'), ('tesis', 'Tesis'), ('manual', 'Manual'), ('web', 'Página Web'), ('otro', 'Otro')], default='libro', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Bibliografía',
                'verbose_name_plural': 'Bibliografías',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='CalculosResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del cálculo/resultado')),
                ('formula', models.TextField(blank=True, verbose_name='Fórmula utilizada')),
                ('procedimiento_calculo', models.TextField(verbose_name='Procedimiento de cálculo')),
                ('resultado_esperado', models.TextField(blank=True, verbose_name='Resultado esperado')),
                ('unidades', models.CharField(blank=True, max_length=50, verbose_name='Unidades de medida')),
                ('margen_error', models.CharField(blank=True, max_length=50, verbose_name='Margen de error aceptable')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_resultados', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Cálculo y Resultado',
                'verbose_name_plural': 'Cálculos y Resultados',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Competencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción de la competencia')),
                ('tipo_competencia', models.CharField(choices=[('conceptual', 'Conceptual'), ('procedimental', 'Procedimental'), ('actitudinal', 'Actitudinal'), ('mixta', 'Mixta')], default='conceptual', max_length=50)),
                ('nivel_desarrollo', models.CharField(choices=[('inicial', 'Inicial'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='inicial', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de desarrollo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['orden', 'tipo_competencia'],
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pregunta', models.PositiveIntegerField(verbose_name='Número de pregunta')),
                ('pregunta', models.TextField(verbose_name='Texto de la pregunta')),
                ('tipo_pregunta', models.CharField(choices=[('abierta', 'Pregunta Abierta'), ('cerrada', 'Pregunta Cerrada'), ('multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso'), ('calculo', 'Cálculo'), ('analisis', 'Análisis')], default='abierta', max_length=50)),
                ('respuesta_esperada', models.TextField(blank=True, verbose_name='Respuesta esperada o criterios')),
                ('puntuacion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Puntuación')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de la pregunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['orden', 'numero_pregunta'],
            },
        ),
        migrations.CreateModel(
            name='FundamentoTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del fundamento')),
                ('contenido', models.TextField(verbose_name='Contenido teórico')),
                ('referencias', models.TextField(blank=True, verbose_name='Referencias adicionales')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de presentación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentos_teoricos', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Fundamento Teórico',
                'verbose_name_plural': 'Fundamentos Teóricos',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MaterialesHerramientasEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del material/herramienta/equipo')),
                ('tipo_elemento', models.CharField(choices=[('material', 'Material'), ('herramienta', 'Herramienta'), ('equipo', 'Equipo'), ('reactivo', 'Reactivo'), ('software', 'Software'), ('otro', 'Otro')], default='material', max_length=50)),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad necesaria')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones técnicas')),
                ('es_obligatorio', models.BooleanField(default=True, verbose_name='¿Es obligatorio?')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de listado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_herramientas_equipos', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Material/Herramienta/Equipo',
                'verbose_name_plural': 'Materiales/Herramientas/Equipos',
                'ordering': ['tipo_elemento', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del objetivo')),
                ('tipo_objetivo', models.CharField(choices=[('general', 'General'), ('especifico', 'Específico'), ('aprendizaje', 'De Aprendizaje'), ('desempeno', 'De Desempeño')], default='especifico', max_length=50)),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden del objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_practica', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Objetivo de la Práctica',
                'verbose_name_plural': 'Objetivos de las Prácticas',
                'ordering': ['orden', 'tipo_objetivo'],
            },
        ),
        migrations.CreateModel(
            name='PracticaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre de la práctica')),
                ('duracion_horas', models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='Duración en horas')),
                ('tipo_practica', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal'), ('demostrativa', 'Demostrativa'), ('virtual', 'Virtual')], default='grupal', max_length=50)),
                ('numero_estudiantes', models.PositiveIntegerField(default=1, verbose_name='Número de estudiantes')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de la práctica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_laboratorio', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Práctica de Laboratorio',
                'verbose_name_plural': 'Prácticas de Laboratorio',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paso', models.PositiveIntegerField(verbose_name='Número del paso')),
                ('titulo_paso', models.CharField(max_length=200, verbose_name='Título del paso')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada del paso')),
                ('tiempo_estimado', models.CharField(blank=True, max_length=50, verbose_name='Tiempo estimado')),
                ('precauciones', models.TextField(blank=True, verbose_name='Precauciones especiales')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden del procedimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'ordering': ['orden', 'numero_paso'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Texto del título')),
                ('nivel', models.PositiveIntegerField(choices=[(1, 'Título Principal'), (2, 'Subtítulo'), (3, 'Sub-subtítulo'), (4, 'Título de Sección'), (5, 'Título de Subsección')], default=1, verbose_name='Nivel del título')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de aparición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenido_analitico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='core.contenidoanalitico')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['orden', 'nivel'],
            },
        ),
    ]
