# Generated by Django 5.2.4 on 2025-10-02 12:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bibliografia_calculosresultados_competencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentoteorico',
            name='contenido',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido teórico'),
        ),
        migrations.AlterField(
            model_name='fundamentoteorico',
            name='referencias',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Referencias adicionales'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción detallada del paso'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='observaciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='precauciones',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Precauciones especiales'),
        ),
    ]
