# Generated by Django 5.2.4 on 2025-10-19 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_fundamentoteorico_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCreacionPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('asignatura_nombre', models.CharField(max_length=300)),
                ('asignatura_id_usado', models.PositiveIntegerField()),
                ('practica_nombre', models.CharField(max_length=500)),
                ('unidad_academica_nombre', models.CharField(max_length=100)),
                ('carrera_nombre', models.CharField(max_length=200)),
                ('semestre', models.PositiveIntegerField()),
                ('asignaturas_similares_detectadas', models.JSONField(default=list)),
                ('confirmacion_usuario', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asignatura')),
                ('contenido_analitico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contenidoanalitico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Creación de Práctica',
                'verbose_name_plural': 'Auditorías de Creación de Prácticas',
                'ordering': ['-created_at'],
            },
        ),
    ]
