# Generated by Django 5.2.4 on 2025-11-10 15:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auditoriacreacionpractica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculosresultados',
            name='procedimiento_calculo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Procedimiento de cálculo'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='pregunta',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto de la pregunta'),
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='respuesta_esperada',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Respuesta esperada o criterios'),
        ),
    ]
