# Generated by Django 5.2.4 on 2025-12-09 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_calculosresultados_procedimiento_calculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalaboratorio',
            name='duracion_horas',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Debe ser entre 0.5 y 8 horas', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(8.0)], verbose_name='Duración en horas'),
        ),
        migrations.AlterField(
            model_name='practicalaboratorio',
            name='numero_estudiantes',
            field=models.PositiveIntegerField(default=1, help_text='Debe ser entre 1 y 100 estudiantes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Número de estudiantes'),
        ),
        migrations.AlterField(
            model_name='practicalaboratorio',
            name='orden',
            field=models.PositiveIntegerField(default=1, help_text='Debe ser mayor a 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Orden de la práctica'),
        ),
        migrations.AddIndex(
            model_name='guialaboratorio',
            index=models.Index(fields=['unidad_tematica', 'numero'], name='core_guiala_unidad__a49155_idx'),
        ),
        migrations.AddIndex(
            model_name='practica',
            index=models.Index(fields=['guia_laboratorio', 'numero'], name='core_practi_guia_la_2dd48c_idx'),
        ),
        migrations.AddIndex(
            model_name='practicalaboratorio',
            index=models.Index(fields=['contenido_analitico', 'orden'], name='core_practi_conteni_4cb206_idx'),
        ),
        migrations.AddIndex(
            model_name='practicalaboratorio',
            index=models.Index(fields=['tipo_practica'], name='core_practi_tipo_pr_e5268b_idx'),
        ),
    ]
