# Generated by Django 5.2.4 on 2025-12-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_practicalaboratorio_duracion_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoanalitico',
            name='criterio_desempeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenidos_analiticos', to='core.criteriodesempeno', verbose_name='Criterio de Desempeño'),
        ),
    ]
