# Generated by Django 5.2.4 on 2025-08-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('reactivos', 'Reactivos Químicos'), ('materiales_laboratorio', 'Materiales de Laboratorio'), ('herramientas', 'Herramientas'), ('consumibles', 'Consumibles'), ('material_vidrio', 'Material de Vidrio'), ('equipos_proteccion', 'Equipos de Protección'), ('material_electronico', 'Material Electrónico'), ('software', 'Software'), ('licencias', 'Licencias'), ('otros', 'Otros')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Insumo',
                'verbose_name_plural': 'Tipos de Insumos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')], verbose_name='Semestre')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Insumo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('cantidad_actual', models.FloatField(default=0, verbose_name='Cantidad Actual')),
                ('cantidad_minima', models.FloatField(default=0, help_text='Cantidad mínima para alertas de stock', verbose_name='Cantidad Mínima')),
                ('cantidad_requerida', models.FloatField(default=0, verbose_name='Cantidad Requerida')),
                ('unidad_medida', models.CharField(choices=[('unidades', 'Unidades'), ('ml', 'Mililitros'), ('l', 'Litros'), ('mg', 'Miligramos'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('m', 'Metros'), ('cm', 'Centímetros'), ('mm', 'Milímetros'), ('piezas', 'Piezas'), ('cajas', 'Cajas'), ('paquetes', 'Paquetes')], default='unidades', max_length=20, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('en_proceso', 'En Proceso de Compra'), ('descartado', 'Descartado')], default='disponible', max_length=20, verbose_name='Estado')),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Estante, cajón, etc.', max_length=200, verbose_name='Ubicación Específica')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('numero_lote', models.CharField(blank=True, max_length=100, verbose_name='Número de Lote')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('es_peligroso', models.BooleanField(default=False, help_text='Requiere manejo especial o EPP', verbose_name='Es Peligroso')),
                ('notas_seguridad', models.TextField(blank=True, verbose_name='Notas de Seguridad')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='insumos/fotos/', verbose_name='Fotografía del Insumo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('codigo_inventario', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura', verbose_name='Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera')),
                ('guia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guialaboratorio', verbose_name='Guía de Laboratorio')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio', verbose_name='Ubicación (Laboratorio)')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practica', verbose_name='Práctica')),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadacademica', verbose_name='Unidad Académica')),
                ('unidad_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadtematica', verbose_name='Unidad Temática')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('tipo_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.tipoinsumo', verbose_name='Tipo de Insumo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['unidad_academica', 'carrera', 'semestre', 'tipo_insumo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de Inventario'), ('descarte', 'Descarte'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.FloatField()),
                ('cantidad_anterior', models.FloatField()),
                ('cantidad_nueva', models.FloatField()),
                ('motivo', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='insumos.insumo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Insumo',
                'verbose_name_plural': 'Movimientos de Insumos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.FloatField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_necesaria', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('justificacion', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cantidad_entregada', models.FloatField(blank=True, null=True)),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_insumos', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='insumos.insumo')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_insumos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Insumo',
                'verbose_name_plural': 'Solicitudes de Insumos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
