# Generated by Django 5.2.4 on 2025-08-20 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrera_nombre'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['unidad_academica', 'carrera', 'categoria', 'nombre_elemento'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_minima',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad_requerida',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='es_peligroso',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fotografia',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='guia_laboratorio',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='notas_seguridad',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='numero_lote',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='practica',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo_insumo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='ubicacion_especifica',
        ),
        migrations.AddField(
            model_name='insumo',
            name='cantidad',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('reactivos', 'Reactivos Químicos'), ('materiales_laboratorio', 'Materiales de Laboratorio'), ('herramientas', 'Herramientas'), ('consumibles', 'Consumibles'), ('material_vidrio', 'Material de Vidrio'), ('equipos_proteccion', 'Equipos de Protección'), ('material_electronico', 'Material Electrónico'), ('software', 'Software'), ('licencias', 'Licencias'), ('otros', 'Otros')], default='consumible', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='condiciones_almacenamiento',
            field=models.CharField(blank=True, choices=[('temperatura_ambiente', 'Temperatura Ambiente'), ('refrigeracion', 'Refrigeración (2-8°C)'), ('congelacion', 'Congelación (-18°C)'), ('lugar_seco', 'Lugar Seco'), ('lugar_oscuro', 'Lugar Oscuro'), ('ventilado', 'Lugar Ventilado'), ('controlado', 'Ambiente Controlado'), ('especial', 'Condiciones Especiales')], max_length=30, null=True, verbose_name='Condiciones de Almacenamiento'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion_caracteristicas',
            field=models.TextField(blank=True, verbose_name='Descripción/Características'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_ingreso_compra',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso/Compra'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='link_fotografia',
            field=models.URLField(blank=True, help_text='URL de la imagen del elemento', verbose_name='Link de la Fotografía del Elemento'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Marca / Modelo'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='nombre_elemento',
            field=models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre del Elemento'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, help_text='Estante, cajón, armario, etc.', max_length=200, verbose_name='Ubicación Física'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='uso_principal',
            field=models.CharField(blank=True, choices=[('ensayos', 'Ensayos de Laboratorio'), ('practicas', 'Prácticas Académicas'), ('investigacion', 'Investigación'), ('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('calibracion', 'Calibración'), ('otros', 'Otros')], max_length=30, null=True, verbose_name='Uso Principal'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='codigo_inventario',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de Inventario (Interno)'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('vencido', 'Vencido'), ('agotado', 'Agotado'), ('descartado', 'Descartado')], default='bueno', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('ml', 'Mililitros'), ('l', 'Litros'), ('mg', 'Miligramos'), ('g', 'Gramos'), ('kg', 'Kilogramos'), ('m', 'Metros'), ('cm', 'Centímetros'), ('mm', 'Milímetros'), ('piezas', 'Piezas'), ('cajas', 'Cajas'), ('paquetes', 'Paquetes'), ('frascos', 'Frascos'), ('sobres', 'Sobres')], default='unidades', max_length=20, verbose_name='Unidad de Medida'),
        ),
    ]
