# Generated by Django 5.2.4 on 2025-08-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_insumo_options_remove_insumo_cantidad_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='codigo_inventario',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Código de Inventario (Interno)'),
        ),
    ]
