# Generated by Django 5.2.4 on 2025-08-24 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asignatura_carga_horaria_semanal_and_more'),
        ('insumos', '0004_alter_insumo_usuario_creador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('reactivos', 'Reactivos'), ('materiales', 'Materiales'), ('herramientas', 'Herramientas')], default='consumible', max_length=50, verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='TareaReordenamientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la tarea a realizar', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('reasignacion', 'Reasignación de Insumos'), ('reubicacion', 'Reubicación de Insumos'), ('cambio_categoria', 'Cambio de Categoría'), ('modificacion_datos', 'Modificación de Datos'), ('transferencia_unidad', 'Transferencia entre Unidades'), ('actualizacion_inventario', 'Actualización de Inventario'), ('control_stock', 'Control de Stock'), ('verificacion_vencimientos', 'Verificación de Vencimientos')], max_length=30, verbose_name='Tipo de Tarea')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Estimada')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('porcentaje_completado', models.IntegerField(default=0, verbose_name='Porcentaje Completado (%)')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_insumos_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_insumos_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Tarea de Reordenamiento de Insumo',
                'verbose_name_plural': 'Tareas de Reordenamiento de Insumos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogReordenamientoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200, verbose_name='Acción Realizada')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='insumos.tareareordenamientoinsumo')),
            ],
            options={
                'verbose_name': 'Log de Reordenamiento de Insumo',
                'verbose_name_plural': 'Logs de Reordenamiento de Insumos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InsumoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_original', models.CharField(blank=True, max_length=50, verbose_name='Categoría Original')),
                ('categoria_objetivo', models.CharField(blank=True, max_length=50, verbose_name='Categoría Objetivo')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('observaciones_procesamiento', models.TextField(blank=True, verbose_name='Observaciones del Procesamiento')),
                ('carrera_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_destino', to='core.carrera', verbose_name='Carrera Objetivo')),
                ('carrera_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_origen', to='core.carrera', verbose_name='Carrera Original')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_reordenamiento', to='insumos.insumo')),
                ('laboratorio_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_destino', to='core.laboratorio', verbose_name='Laboratorio Objetivo')),
                ('laboratorio_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_origen', to='core.laboratorio', verbose_name='Laboratorio Original')),
                ('unidad_academica_objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_destino', to='core.unidadacademica', verbose_name='Unidad Académica Objetivo')),
                ('unidad_academica_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_tareas_origen', to='core.unidadacademica', verbose_name='Unidad Académica Original')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='insumos.tareareordenamientoinsumo')),
            ],
            options={
                'verbose_name': 'Insumo en Tarea',
                'verbose_name_plural': 'Insumos en Tareas',
                'unique_together': {('tarea', 'insumo')},
            },
        ),
    ]
