# Generated by Django 5.2.4 on 2025-08-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_asignatura_carga_horaria_semanal_and_more'),
        ('insumos', '0005_alter_insumo_categoria_tareareordenamientoinsumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='guia_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guialaboratorio', verbose_name='Guía de Laboratorio'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.practica', verbose_name='Práctica'),
        ),
    ]
