# Generated by Django 5.2.4 on 2025-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_insumo_guia_laboratorio_insumo_practica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='codigo_inventario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Inventario (Interno)'),
        ),
    ]
