# Generated by Django 5.2.4 on 2025-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_fix_codigo_inventario_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(choices=[('reactivos', 'Reactivos'), ('materiales', 'Materiales'), ('herramientas', 'Herramientas')], default='reactivos', max_length=50, verbose_name='Categoría'),
        ),
    ]
