# Generated by Django 5.2.4 on 2025-12-09 17:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_calculosresultados_procedimiento_calculo_and_more'),
        ('insumos', '0008_alter_insumo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['unidad_academica', 'laboratorio', 'categoria', 'nombre_elemento'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['estado'], name='insumos_ins_estado_b2a35d_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['categoria'], name='insumos_ins_categor_6f212a_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['created_at'], name='insumos_ins_created_b32825_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['unidad_academica', 'laboratorio'], name='insumos_ins_unidad__525291_idx'),
        ),
    ]
