# Generated by Django 5.2.4 on 2025-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_alter_insumo_options_alter_insumo_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='seccion',
            field=models.CharField(choices=[('academico', 'Académico'), ('investigacion', 'Investigación'), ('produccion', 'Producción')], db_index=True, default='academico', help_text='Sección a la que pertenece el insumo', max_length=20, verbose_name='Sección'),
        ),
    ]
