# Generated by Django 5.2.4 on 2025-07-14 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ingenieria_sistemas', 'Ingeniería de Sistemas'), ('ingenieria_civil', 'Ingeniería Civil'), ('ingenieria_industrial', 'Ingeniería Industrial'), ('ingenieria_electronica', 'Ingeniería Electrónica'), ('ingenieria_mecanica', 'Ingeniería Mecánica'), ('ingenieria_quimica', 'Ingeniería Química'), ('ingenieria_petrolera', 'Ingeniería Petrolera'), ('ingenieria_ambiental', 'Ingeniería Ambiental')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('microscopio_optico', 'Microscopio Óptico'), ('balanza_analitica', 'Balanza Analítica'), ('espectrofotometro', 'Espectrofotómetro'), ('centrifuga', 'Centrífuga'), ('autoclave', 'Autoclave'), ('incubadora', 'Incubadora'), ('ph_metro', 'pH Metro'), ('agitador_magnetico', 'Agitador Magnético'), ('campana_extractora', 'Campana Extractora'), ('mechero_bunsen', 'Mechero Bunsen')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('la_paz', 'La Paz'), ('cochabamba', 'Cochabamba'), ('santa_cruz', 'Santa Cruz'), ('riberalta', 'Riberalta'), ('tropico', 'Trópico')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidad Académica',
                'verbose_name_plural': 'Unidades Académicas',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='ingreso_datos.laboratorio')),
            ],
            options={
                'verbose_name': 'Ensayo',
                'verbose_name_plural': 'Ensayos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('semestre', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'unique_together': {('nombre', 'carrera', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.materia'),
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('datos_completos', models.JSONField()),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ingreso',
                'verbose_name_plural': 'Registros de Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo')], default='operativo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ingreso_datos.ensayo')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadacademica'),
        ),
    ]
