# Generated by Django 5.2.4 on 2025-08-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[], max_length=50)),
                ('semestre', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')])),
                ('carga_horaria_semanal', models.IntegerField(help_text='Horas por semana')),
                ('carga_horaria_semestral', models.IntegerField(help_text='Total de horas en el semestre')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ingenieria_ambiental', 'Ingeniería Ambiental'), ('ingenieria_civil', 'Ingeniería Civil'), ('ingenieria_sistemas_electronicos', 'Ingeniería en Sistemas Electrónicos'), ('ingenieria_comercial', 'Ingeniería Comercial'), ('ingenieria_sistemas', 'Ingeniería de Sistemas'), ('ingenieria_agroindustrial', 'Ingeniería Agroindustrial'), ('sistemas_electronicos', 'Sistemas Electrónicos'), ('informatica', 'Informática'), ('construccion_civil', 'Construcción Civil'), ('energias_renovables', 'Energías Renovables'), ('diseno_grafico', 'Diseño Gráfico y Comunicación Audiovisual')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='GuiaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la guía')),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Guía de Laboratorio',
                'verbose_name_plural': 'Guías de Laboratorio',
                'ordering': ['unidad_tematica', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('lab_fisica_mecanica', 'Laboratorio de Física Mecánica'), ('lab_quimica_general', 'Laboratorio de Química General'), ('lab_electronica_basica', 'Laboratorio de Electrónica Básica'), ('lab_programacion', 'Laboratorio de Programación'), ('lab_circuitos_electricos', 'Laboratorio de Circuitos Eléctricos'), ('lab_materiales_resistencia', 'Laboratorio de Materiales y Resistencia'), ('lab_fluidos_termodinamica', 'Laboratorio de Fluidos y Termodinámica'), ('lab_sistemas_control', 'Laboratorio de Sistemas de Control'), ('lab_redes_computadoras', 'Laboratorio de Redes de Computadoras'), ('lab_automatizacion', 'Laboratorio de Automatización Industrial')], max_length=50)),
                ('seccion_area', models.CharField(help_text='Sección o área del laboratorio', max_length=100)),
                ('identificador_aula', models.CharField(help_text='Número o identificador del aula', max_length=50)),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nombre_display', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
            },
        ),
        migrations.CreateModel(
            name='UnidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('la_paz', 'La Paz'), ('cochabamba', 'Cochabamba'), ('santa_cruz', 'Santa Cruz'), ('riberalta', 'Riberalta'), ('tropico', 'Trópico')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Unidad Académica',
                'verbose_name_plural': 'Unidades Académicas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
            ],
            options={
                'verbose_name': 'Materia (Deprecado)',
                'verbose_name_plural': 'Materias (Deprecadas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ingreso_datos.asignatura',),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.carrera'),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la práctica')),
                ('descripcion', models.TextField(blank=True)),
                ('guia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='ingreso_datos.guialaboratorio')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
                'ordering': ['guia_laboratorio', 'numero'],
                'unique_together': {('guia_laboratorio', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RegistroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('datos_completos', models.JSONField()),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.laboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ingreso (Deprecado)',
                'verbose_name_plural': 'Registros de Ingresos (Deprecados)',
            },
        ),
        migrations.CreateModel(
            name='EquipoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado_fisico', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20)),
                ('estado_operativo', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo')], default='operativo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_individuales', to='ingreso_datos.tipoequipo')),
                ('unidad_academica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadacademica')),
            ],
            options={
                'verbose_name': 'Equipo Individual (Deprecado)',
                'verbose_name_plural': 'Equipos Individuales (Deprecados)',
            },
        ),
        migrations.CreateModel(
            name='EquipoExistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('inoperativo', 'Inoperativo')], default='bueno', max_length=20)),
                ('numero_unidades', models.IntegerField(default=1, help_text='Número de unidades de este equipo')),
                ('es_activo_fijo', models.BooleanField(default=False, help_text='¿Es un activo fijo según acta de entrega?')),
                ('fotografia_frontal', models.ImageField(blank=True, null=True, upload_to='equipos/fotos_frontales/')),
                ('fotografia_placa', models.ImageField(blank=True, null=True, upload_to='equipos/fotos_placas/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_existentes', to='ingreso_datos.laboratorio')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo Existente',
                'verbose_name_plural': 'Equipos Existentes',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipos_seleccionados', models.ManyToManyField(blank=True, to='ingreso_datos.equipoindividual')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo (Deprecado)',
                'verbose_name_plural': 'Equipos (Deprecados)',
            },
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='unidad_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadacademica'),
        ),
        migrations.CreateModel(
            name='UnidadTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.IntegerField(help_text='Número de la unidad temática')),
                ('descripcion', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_tematicas', to='ingreso_datos.asignatura')),
            ],
            options={
                'verbose_name': 'Unidad Temática',
                'verbose_name_plural': 'Unidades Temáticas',
                'ordering': ['asignatura', 'numero'],
                'unique_together': {('asignatura', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RegistroEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.carrera')),
                ('guia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.guialaboratorio')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.laboratorio')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.practica')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadacademica')),
                ('unidad_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadtematica')),
            ],
            options={
                'verbose_name': 'Registro de Equipos',
                'verbose_name_plural': 'Registros de Equipos',
            },
        ),
        migrations.AddField(
            model_name='guialaboratorio',
            name='unidad_tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias_laboratorio', to='ingreso_datos.unidadtematica'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('nombre', 'carrera', 'semestre')},
        ),
        migrations.CreateModel(
            name='EquipoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipos_requeridos', models.IntegerField(help_text='Número de equipos necesarios')),
                ('especificaciones', models.TextField(blank=True, help_text='Especificaciones técnicas requeridas')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_requeridos', to='ingreso_datos.practica')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo Requerido',
                'verbose_name_plural': 'Equipos Requeridos',
                'unique_together': {('practica', 'tipo_equipo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='guialaboratorio',
            unique_together={('unidad_tematica', 'numero')},
        ),
    ]
