# Generated by Django 5.2.4 on 2025-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
