# Generated by Django 5.2.4 on 2025-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0002_alter_materia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='nombre',
            field=models.CharField(choices=[('lab_fisica_mecanica', 'Laboratorio de Física Mecánica'), ('lab_quimica_general', 'Laboratorio de Química General'), ('lab_electronica_basica', 'Laboratorio de Electrónica Básica'), ('lab_programacion', 'Laboratorio de Programación'), ('lab_circuitos_electricos', 'Laboratorio de Circuitos Eléctricos'), ('lab_materiales_resistencia', 'Laboratorio de Materiales y Resistencia'), ('lab_fluidos_termodinamica', 'Laboratorio de Fluidos y Termodinámica'), ('lab_sistemas_control', 'Laboratorio de Sistemas de Control'), ('lab_redes_computadoras', 'Laboratorio de Redes de Computadoras'), ('lab_automatizacion', 'Laboratorio de Automatización Industrial')], max_length=50),
        ),
    ]
