# Generated by Django 5.2.4 on 2025-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0003_remove_laboratorio_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='nombre',
            field=models.CharField(choices=[('ensayo_traccion', 'Ensayo de Tracción'), ('ensayo_compresion', 'Ensayo de Compresión'), ('ensayo_dureza', 'Ensayo de Dureza'), ('ensayo_impacto', 'Ensayo de Impacto'), ('ensayo_ph', 'Ensayo de pH'), ('ensayo_conductividad', 'Ensayo de Conductividad Eléctrica'), ('ensayo_densidad', 'Ensayo de Densidad'), ('ensayo_viscosidad', 'Ensayo de Viscosidad'), ('ensayo_microscopia', 'Ensayo de Microscopía'), ('ensayo_espectroscopia', 'Ensayo de Espectroscopía')], max_length=50),
        ),
    ]
