# Generated by Django 5.2.4 on 2025-07-14 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0004_alter_ensayo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='estado',
        ),
        migrations.AddField(
            model_name='ensayo',
            name='cantidad_estudiantes',
            field=models.IntegerField(default=1, help_text='Número de estudiantes que participarán en el ensayo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cantidad_necesaria',
            field=models.IntegerField(default=1, help_text='Cantidad de equipos necesarios para el ensayo'),
        ),
        migrations.AddField(
            model_name='tipoequipo',
            name='capacidad_estudiantes',
            field=models.IntegerField(default=1, help_text='Número de estudiantes que pueden usar simultáneamente este equipo'),
        ),
        migrations.CreateModel(
            name='EquipoIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del equipo', max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo')], default='operativo', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_individuales', to='ingreso_datos.tipoequipo')),
            ],
            options={
                'verbose_name': 'Equipo Individual',
                'verbose_name_plural': 'Equipos Individuales',
                'ordering': ['tipo_equipo', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='equipos_seleccionados',
            field=models.ManyToManyField(blank=True, to='ingreso_datos.equipoindividual'),
        ),
    ]
