# Generated by Django 5.2.4 on 2025-07-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0005_remove_equipo_cantidad_remove_equipo_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipoindividual',
            name='estado',
        ),
        migrations.AddField(
            model_name='equipoindividual',
            name='estado_fisico',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', help_text='Estado físico del equipo', max_length=20),
        ),
        migrations.AddField(
            model_name='equipoindividual',
            name='estado_operativo',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo')], default='operativo', help_text='Estado operativo del equipo', max_length=20),
        ),
    ]
