# Generated by Django 5.2.4 on 2025-07-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0006_remove_equipoindividual_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipo',
            name='nombre_display',
            field=models.CharField(blank=True, help_text='Nombre para mostrar en la interfaz', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='nombre',
            field=models.CharField(help_text='Identificador único del tipo de equipo', max_length=50, unique=True),
        ),
    ]
