# Generated by Django 5.2.4 on 2025-07-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_datos', '0007_tipoequipo_nombre_display_alter_tipoequipo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoindividual',
            name='unidad_academica',
            field=models.ForeignKey(blank=True, help_text='Unidad académica donde se encuentra el equipo', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingreso_datos.unidadacademica'),
        ),
    ]
