# Generated by Django 5.2.4 on 2025-08-20 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_carrera_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre'), ('3', 'Tercer Semestre'), ('4', 'Cuarto Semestre'), ('5', 'Quinto Semestre'), ('6', 'Sexto Semestre'), ('7', 'Séptimo Semestre'), ('8', 'Octavo Semestre'), ('9', 'Noveno Semestre'), ('10', 'Décimo Semestre')], max_length=2)),
                ('contenido_analitico', models.TextField()),
                ('unidad_didactica', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_word', models.FileField(blank=True, upload_to='guias/word/')),
                ('archivo_pdf', models.FileField(blank=True, upload_to='guias/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guía Generada',
                'verbose_name_plural': 'Guías Generadas',
                'ordering': ['-created_at'],
            },
        ),
    ]
