# Generated by Django 5.2.4 on 2025-09-28 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unidadacademica_nombre'),
        ('equipos', '0005_remove_equipo_unidad_tematica_and_more'),
        ('guias', '0002_auto_20250819_2219'),
        ('insumos', '0008_alter_insumo_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guiagenerada',
            name='codigo_guia',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de la Guía'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='competencias',
            field=models.TextField(default='none', help_text='Competencias específicas que desarrolla esta práctica', verbose_name='Competencias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='criterios_evaluacion',
            field=models.TextField(blank=True, help_text='Criterios para evaluar el desempeño del estudiante', verbose_name='Criterios de Evaluación'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='cuestionario',
            field=models.TextField(default='none', help_text='Preguntas de evaluación y análisis de resultados', verbose_name='Cuestionario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=2, verbose_name='Duración en Horas'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='equipos_requeridos',
            field=models.ManyToManyField(blank=True, help_text='Equipos necesarios para esta práctica', to='equipos.equipo', verbose_name='Equipos Requeridos'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('publicada', 'Publicada')], default='borrador', max_length=20, verbose_name='Estado de la Guía'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='insumos_requeridos',
            field=models.ManyToManyField(blank=True, help_text='Insumos y materiales necesarios', to='insumos.insumo', verbose_name='Insumos Requeridos'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='medidas_seguridad',
            field=models.TextField(blank=True, help_text='Normas de seguridad a considerar', verbose_name='Medidas de Seguridad'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='numero_practica',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Práctica'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='objetivo_general',
            field=models.TextField(default='none', help_text='Objetivo general de la práctica de laboratorio', verbose_name='Objetivo General'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='objetivos_especificos',
            field=models.TextField(blank=True, help_text='Objetivos específicos detallados', verbose_name='Objetivos Específicos'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales para el instructor', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='preparacion_previa',
            field=models.TextField(blank=True, help_text='Actividades que el estudiante debe realizar antes de la práctica', verbose_name='Preparación Previa'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='procedimientos',
            field=models.TextField(default='none', help_text='Pasos detallados para realizar la práctica', verbose_name='Procedimientos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='referencia_bibliografica',
            field=models.TextField(blank=True, help_text='Referencias bibliográficas y fuentes consultadas', verbose_name='Referencia Bibliográfica'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='resultados_esperados',
            field=models.TextField(blank=True, help_text='Resultados que se esperan obtener', verbose_name='Resultados Esperados'),
        ),
        migrations.AddField(
            model_name='guiagenerada',
            name='tipo_practica',
            field=models.CharField(choices=[('laboratorio', 'Práctica de Laboratorio'), ('campo', 'Práctica de Campo'), ('simulacion', 'Simulación'), ('proyecto', 'Proyecto'), ('investigacion', 'Investigación')], default='laboratorio', max_length=50, verbose_name='Tipo de Práctica'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='archivo_pdf',
            field=models.FileField(blank=True, upload_to='guias/pdf/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='archivo_word',
            field=models.FileField(blank=True, upload_to='guias/word/', verbose_name='Archivo Word'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='contenido_analitico',
            field=models.TextField(verbose_name='Contenido Analítico'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre'), ('3', 'Tercer Semestre'), ('4', 'Cuarto Semestre'), ('5', 'Quinto Semestre'), ('6', 'Sexto Semestre'), ('7', 'Séptimo Semestre'), ('8', 'Octavo Semestre'), ('9', 'Noveno Semestre'), ('10', 'Décimo Semestre')], max_length=2, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título de la Guía'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='unidad_didactica',
            field=models.CharField(max_length=200, verbose_name='Unidad Didáctica'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
