# Generated by Django 5.2.4 on 2025-12-09 18:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_practicalaboratorio_duracion_horas_and_more'),
        ('equipos', '0008_alter_equipo_carga_horaria_semanal_and_more'),
        ('guias', '0003_guiagenerada_codigo_guia_guiagenerada_competencias_and_more'),
        ('insumos', '0009_alter_insumo_options_alter_insumo_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiagenerada',
            options={'ordering': ['-created_at', 'carrera', 'asignatura', 'numero_practica'], 'verbose_name': 'Guía Generada', 'verbose_name_plural': 'Guías Generadas'},
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=2, help_text='Debe ser entre 1 y 8 horas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Duración en Horas'),
        ),
        migrations.AlterField(
            model_name='guiagenerada',
            name='numero_practica',
            field=models.PositiveIntegerField(default=1, help_text='Debe ser mayor a 0', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Práctica'),
        ),
        migrations.AddIndex(
            model_name='guiagenerada',
            index=models.Index(fields=['-created_at'], name='guias_guiag_created_5a4933_idx'),
        ),
        migrations.AddIndex(
            model_name='guiagenerada',
            index=models.Index(fields=['carrera', 'asignatura'], name='guias_guiag_carrera_c12c79_idx'),
        ),
        migrations.AddIndex(
            model_name='guiagenerada',
            index=models.Index(fields=['carrera', 'semestre'], name='guias_guiag_carrera_62f3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='guiagenerada',
            index=models.Index(fields=['tipo_practica', 'created_at'], name='guias_guiag_tipo_pr_b7442c_idx'),
        ),
    ]
