# Generated by Django 5.2.4 on 2025-08-28 19:31

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_asignatura_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('tipo_documento', models.CharField(choices=[('ci', 'Cédula de Identidad'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='ci', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números')], verbose_name='Número de Documento de Identidad')),
                ('telefono_personal', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-\\(\\)]+$', 'Formato de teléfono inválido')], verbose_name='Teléfono Personal')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto de Perfil')),
                ('especialidad_area', models.CharField(blank=True, max_length=200, verbose_name='Especialidad/Área de Conocimiento')),
                ('nivel_formacion', models.CharField(blank=True, choices=[('ingeniero', 'Ingeniero'), ('licenciado', 'Licenciado'), ('tecnico_superior', 'Técnico Superior'), ('tecnico_medio', 'Técnico Medio'), ('otro', 'Otro')], max_length=20, verbose_name='Nivel de Formación')),
                ('area_formacion', models.CharField(blank=True, max_length=200, verbose_name='Área de Formación')),
                ('experiencia_laboratorios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Experiencia en Laboratorios (años)')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('jefe_uycit', 'Jefe UYCIT'), ('auxiliar', 'Auxiliar/Encargado de Laboratorio')], max_length=20, verbose_name='Rol en el Sistema')),
                ('sede_asignacion', models.CharField(choices=[('UALP', 'Unidad Académica La Paz'), ('UACB', 'Unidad Académica Cochabamba'), ('UASC', 'Unidad Académica Santa Cruz'), ('UATP', 'Unidad Académica Trópico'), ('UARB', 'Unidad Académica Riberalta')], max_length=10, verbose_name='Sede de Asignación')),
                ('cargo_posicion', models.CharField(blank=True, max_length=200, verbose_name='Cargo/Posición Institucional')),
                ('unidad', models.CharField(blank=True, max_length=200, verbose_name='Unidad')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo Institucional')),
                ('turno_trabajo', models.CharField(blank=True, choices=[('grado', 'Grado'), ('tecnologico', 'Tecnológico')], max_length=20, verbose_name='Turno de Trabajo')),
                ('descripcion_responsabilidades', models.TextField(blank=True, verbose_name='Descripción de Responsabilidades')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado_usuario', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido Temporalmente')], default='activo', max_length=20, verbose_name='Estado del Usuario')),
                ('debe_cambiar_password', models.BooleanField(default=True, verbose_name='Debe cambiar contraseña en el próximo acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('jefe_superior', models.ForeignKey(blank=True, limit_choices_to={'rol': 'jefe_uycit'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Jefe Inmediato Superior')),
                ('laboratorios_asignados', models.ManyToManyField(blank=True, to='core.laboratorio', verbose_name='Laboratorios Asignados')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['apellidos', 'nombres'],
            },
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('gestion_equipos', 'Gestión de Equipos'), ('gestion_insumos', 'Gestión de Insumos'), ('supervision_guias', 'Supervisión de Guías de Laboratorio'), ('investigacion_servicios', 'Investigación y Servicios'), ('administracion_usuarios', 'Administración de Usuarios'), ('dashboard_reordenamiento', 'Dashboard de Reordenamiento')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
                'unique_together': {('usuario', 'area')},
            },
        ),
    ]
