# Generated by Django 5.2.4 on 2025-08-28 21:11

import django.core.validators
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_institucional',
            field=models.EmailField(max_length=254, unique=True, validators=[usuarios.models.validar_correo_institucional], verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números')], verbose_name='Número de Carnet de Identidad'),
        ),
    ]
