# Generated by Django 5.2.4 on 2025-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('docente', 'Docente'), ('jefe_uycit', 'Jefe UYCIT'), ('auxiliar', 'Auxiliar/Encargado de Laboratorio')], max_length=20, verbose_name='Rol en el Sistema'),
        ),
    ]
