# Generated by Django 5.2.4 on 2025-08-16 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')], verbose_name='Semestre')),
                ('carga_horaria_semanal', models.IntegerField(help_text='Horas por semana', verbose_name='Carga Horaria Semanal')),
                ('carga_horaria_semestral', models.IntegerField(help_text='Total de horas en el semestre', verbose_name='Carga Horaria Semestral')),
                ('equipo_existente', models.CharField(help_text='Nombre del equipo existente', max_length=200, verbose_name='Equipo Existente')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo'), ('nuevo', 'Nuevo'), ('usado', 'Usado'), ('descartado', 'Descartado')], default='operativo', max_length=20, verbose_name='Estado')),
                ('numero_unidades', models.IntegerField(default=1, verbose_name='Número de Unidades del Equipo')),
                ('es_activo_fijo', models.BooleanField(default=False, verbose_name='Es un Activo Fijo de acuerdo a su Acta de Entrega?')),
                ('fotografia_frontal', models.ImageField(blank=True, null=True, upload_to='equipos/fotos_frontales/', verbose_name='Fotografía Frontal del Equipo')),
                ('fotografia_placa', models.ImageField(blank=True, null=True, upload_to='equipos/fotos_placas/', verbose_name='Fotografía de la Placa de Características')),
                ('seccion_area', models.CharField(blank=True, max_length=100, verbose_name='Sección/Área')),
                ('identificador_aula', models.CharField(blank=True, max_length=50, verbose_name='Identificador/Nº de Aula')),
                ('equipo_requerido', models.CharField(blank=True, help_text='Equipo que se requiere para completar el laboratorio', max_length=200, verbose_name='Equipo Requerido')),
                ('numero_equipos_requeridos', models.IntegerField(default=0, verbose_name='Número de Equipos Requeridos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('codigo_inventario', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asignatura', verbose_name='Asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera')),
                ('guia_laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guialaboratorio', verbose_name='Guía de Laboratorio')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorio', verbose_name='Ubicación del Equipo (Laboratorio)')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practica', verbose_name='Práctica')),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadacademica', verbose_name='Unidad Académica')),
                ('unidad_tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadtematica', verbose_name='Unidad Temática')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['unidad_academica', 'carrera', 'semestre', 'asignatura'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo'), ('nuevo', 'Nuevo'), ('usado', 'Usado'), ('descartado', 'Descartado')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('inoperativo', 'Inoperativo'), ('nuevo', 'Nuevo'), ('usado', 'Usado'), ('descartado', 'Descartado')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='equipos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historiales de Equipos',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('calibracion', 'Calibración'), ('reparacion', 'Reparación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='equipos.equipo')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mantenimiento de Equipo',
                'verbose_name_plural': 'Mantenimientos de Equipos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
