# Generated by Django 5.2.4 on 2025-08-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrera_nombre'),
        ('equipos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaReordenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la tarea a realizar', verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('reasignacion', 'Reasignación de Equipos'), ('reubicacion', 'Reubicación de Equipos'), ('cambio_caracteristicas', 'Cambio de Características'), ('modificacion_datos', 'Modificación de Datos'), ('transferencia_unidad', 'Transferencia entre Unidades'), ('actualizacion_inventario', 'Actualización de Inventario')], max_length=30, verbose_name='Tipo de Tarea')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Estimada')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('porcentaje_completado', models.IntegerField(default=0, verbose_name='Porcentaje Completado (%)')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Tarea de Reordenamiento',
                'verbose_name_plural': 'Tareas de Reordenamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogReordenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Acción')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipos.tareareordenamiento')),
            ],
            options={
                'verbose_name': 'Log de Reordenamiento',
                'verbose_name_plural': 'Logs de Reordenamiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EquipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesado', models.BooleanField(default=False, verbose_name='Procesado')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesado')),
                ('observaciones_equipo', models.TextField(blank=True, verbose_name='Observaciones del Equipo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_reordenamiento', to='equipos.equipo')),
                ('laboratorio_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_destino', to='core.laboratorio', verbose_name='Laboratorio Destino')),
                ('laboratorio_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_origen', to='core.laboratorio', verbose_name='Laboratorio Origen')),
                ('unidad_academica_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_destino', to='core.unidadacademica', verbose_name='Unidad Académica Destino')),
                ('unidad_academica_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_origen', to='core.unidadacademica', verbose_name='Unidad Académica Origen')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_involucrados', to='equipos.tareareordenamiento')),
            ],
            options={
                'verbose_name': 'Equipo en Tarea',
                'verbose_name_plural': 'Equipos en Tareas',
                'unique_together': {('tarea', 'equipo')},
            },
        ),
    ]
