# Generated by Django 5.2.4 on 2025-08-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_tareareordenamiento_logreordenamiento_equipotarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='responsable_excel',
            field=models.CharField(blank=True, help_text='Nombre del responsable según los datos importados del Excel', max_length=200, verbose_name='Responsable (del Excel)'),
        ),
    ]
