# Generated by Django 5.2.4 on 2025-08-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipo_responsable_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='estado_anterior',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='estado_nuevo',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20),
        ),
    ]
