# Generated by Django 5.2.4 on 2025-09-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_criteriodesempeno_unidaddidactica_contenidoanalitico'),
        ('equipos', '0004_actualizar_estados_oficiales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='unidad_tematica',
        ),
        migrations.AddField(
            model_name='equipo',
            name='contenido_analitico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contenidoanalitico', verbose_name='Contenido Analítico'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='criterio_desempeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.criteriodesempeno', verbose_name='Criterio de Desempeño'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='unidad_didactica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidaddidactica', verbose_name='Unidad Didáctica'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='equipo_existente',
            field=models.CharField(help_text='Nombre del equipo existente', max_length=200, verbose_name='Nombre de Equipo Existente'),
        ),
    ]
