# Generated by Django 5.2.4 on 2025-10-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_remove_equipo_unidad_tematica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True, verbose_name='N')),
                ('unidad_academica', models.CharField(max_length=50, verbose_name='Unidad Académica')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('ci', models.CharField(blank=True, max_length=50, verbose_name='C.I.')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('oficina', models.CharField(blank=True, max_length=200, verbose_name='Oficina')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('descripcion_activo', models.TextField(verbose_name='Descripción del Activo')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('fecha_asignacion', models.CharField(blank=True, max_length=50, verbose_name='Fecha de Asignación')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Importación')),
            ],
            options={
                'verbose_name': 'Equipo Importado',
                'verbose_name_plural': 'Equipos Importados',
                'ordering': ['numero'],
            },
        ),
    ]
