# Generated by Django 5.2.4 on 2025-10-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_equipoimportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cargo_responsable',
            field=models.CharField(blank=True, help_text='Cargo que ocupa el responsable', max_length=200, verbose_name='Cargo del Responsable'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ci_responsable',
            field=models.CharField(blank=True, help_text='Cédula de identidad del responsable', max_length=20, verbose_name='C.I. del Responsable'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='codigo_excel',
            field=models.CharField(blank=True, help_text='Código del equipo según el archivo Excel', max_length=50, verbose_name='Código (del Excel)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='descripcion_excel',
            field=models.TextField(blank=True, help_text='Descripción detallada del activo según el Excel', verbose_name='Descripción del Activo (del Excel)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_asignacion',
            field=models.DateField(blank=True, help_text='Fecha en que fue asignado el equipo', null=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='oficina',
            field=models.CharField(blank=True, help_text='Oficina donde se encuentra ubicado', max_length=200, verbose_name='Oficina'),
        ),
    ]
