# Generated by Django 5.2.4 on 2025-12-09 17:55

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_calculosresultados_procedimiento_calculo_and_more'),
        ('equipos', '0007_equipo_cargo_responsable_equipo_ci_responsable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='carga_horaria_semanal',
            field=models.IntegerField(help_text='Horas por semana', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carga Horaria Semanal'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='carga_horaria_semestral',
            field=models.IntegerField(help_text='Total de horas en el semestre', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carga Horaria Semestral'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_equipos_requeridos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Equipos Requeridos'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_unidades',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Unidades del Equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado'], name='equipos_equ_estado_333e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['created_at'], name='equipos_equ_created_18fbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['unidad_academica', 'carrera'], name='equipos_equ_unidad__1ce944_idx'),
        ),
    ]
