# Generated by Django 5.2.4 on 2025-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_alter_equipo_carga_horaria_semanal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='seccion',
            field=models.CharField(choices=[('academico', 'Académico'), ('investigacion', 'Investigación'), ('produccion', 'Producción')], db_index=True, default='academico', help_text='Sección a la que pertenece el equipo', max_length=20, verbose_name='Sección'),
        ),
    ]
