# Generated by Django 5.2.4 on 2025-12-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contenidoanalitico_criterio_desempeno'),
        ('equipos', '0009_equipo_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='guia_laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guialaboratorio', verbose_name='Guía de Laboratorio'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.practica', verbose_name='Práctica'),
        ),
    ]
