# Generated by Django 5.2.4 on 2025-10-19 03:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_auditoriacreacionpractica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(help_text='Código único del activo fijo', max_length=50, unique=True, verbose_name='Código Patrimonial')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del activo fijo', max_length=200, verbose_name='Nombre del Activo')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del activo, características, especificaciones', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('equipos_computo', 'Equipos de Cómputo'), ('mobiliario', 'Mobiliario y Enseres'), ('vehiculos', 'Vehículos'), ('maquinaria', 'Maquinaria y Equipos'), ('equipos_laboratorio', 'Equipos de Laboratorio'), ('equipos_audiovisuales', 'Equipos Audiovisuales'), ('instrumentos', 'Instrumentos y Herramientas'), ('infraestructura', 'Infraestructura'), ('bibliotecas', 'Material Bibliográfico'), ('otros', 'Otros Activos')], help_text='Tipo/categoría del activo fijo', max_length=50, verbose_name='Categoría')),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, help_text='Valor original de compra en bolivianos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor de Adquisición (Bs.)')),
                ('valor_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor actual considerando depreciación', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Actual (Bs.)')),
                ('fecha_adquisicion', models.DateField(help_text='Fecha en que se adquirió el activo', verbose_name='Fecha de Adquisición')),
                ('metodo_adquisicion', models.CharField(choices=[('compra', 'Compra Directa'), ('licitacion', 'Licitación Pública'), ('donacion', 'Donación'), ('transferencia', 'Transferencia'), ('intercambio', 'Intercambio'), ('fabricacion_propia', 'Fabricación Propia'), ('arrendamiento', 'Arrendamiento Financiero'), ('otros', 'Otros Métodos')], max_length=50, verbose_name='Método de Adquisición')),
                ('proveedor', models.CharField(blank=True, help_text='Empresa o entidad proveedora', max_length=200, verbose_name='Proveedor')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('año_fabricacion', models.IntegerField(blank=True, null=True, verbose_name='Año de Fabricación')),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Edificio, aula, oficina, etc.', max_length=200, verbose_name='Ubicación Física')),
                ('estado_fisico', models.CharField(choices=[('excelente', 'Excelente'), ('muy_bueno', 'Muy Bueno'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('inservible', 'Inservible'), ('en_reparacion', 'En Reparación'), ('dado_de_baja', 'Dado de Baja')], default='bueno', max_length=50, verbose_name='Estado Físico')),
                ('estado_operativo', models.CharField(choices=[('operativo', 'Operativo'), ('no_operativo', 'No Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('fuera_de_servicio', 'Fuera de Servicio'), ('pendiente_revision', 'Pendiente de Revisión'), ('en_prestamo', 'En Préstamo'), ('almacenado', 'Almacenado'), ('transferido', 'Transferido')], default='operativo', max_length=50, verbose_name='Estado Operativo')),
                ('responsable', models.CharField(blank=True, help_text='Nombre de la persona responsable', max_length=200, verbose_name='Responsable Actual')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrera', verbose_name='Carrera')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratorio', verbose_name='Laboratorio')),
                ('unidad_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadacademica', verbose_name='Unidad Académica')),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
                'ordering': ['codigo_patrimonial'],
            },
        ),
    ]
